#source ./common.sh

#echo Copy MongoDB repo file
#cp mongo.repo /etc/yum.repos.d/mongo.repo &>>$log_file
#Status_Print $?
- name: Copy MongoDB Repo File
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

#echo Install MongoDB
#dnf install mongodb-org -y &>>$log_file
#Status_Print $?
- name: Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed

#echo Start MongoDB service
#systemctl enable mongod &>>$log_file
- name: Enable and Start MongoDB
  ansible.builtin.systemd_service:
    name: mongod
    state: started
    enabled: true

#echo Update MongoDB listen address
#sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf &>>$log_file
#Status_Print $?
- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'


#systemctl restart mongod &>>$log_file
#Status_Print $?
- name: Restart MongoDB
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted