#dnf module disable nginx -y &>>$log_file
#Status_Print $?
- name: Disable Default Nginx Version
  ansible.builtin.shell: dnf module disable nginx -y

#dnf module enable nginx:1.24 -y &>>$log_file
#Status_Print $?
- name: Enable Nginx 1.24 Version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

#dnf install nginx -y &>>$log_file
#Status_Print $?
- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

#cp nginx.conf /etc/nginx/nginx.conf &>>$log_file
#Status_Print $?
- name: Copy Nginx Config file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

#rm -rf /usr/share/nginx/html/* &>>$log_file
#Status_Print $?

- name: Remove Nginx Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Nginx Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#rm -f /tmp/frontend.zip &>>$log_file
#Status_Print $?

#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip &>>$log_file
#Status_Print $?

#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip &>>$log_file
#Status_Print $?
- name: Download and extract frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

#systemctl enable nginx
#systemctl restart nginx &>>$log_file
#Status_Print $?
- name: Start Nginx service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true
#######################################


