- name: Disable Default Nginx Version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 1.24 Version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy Nginx Config File
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove Nginx Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Nginx Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and Extract Frontend Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

# systemctl enable nginx
- name: Enable Nginx
  ansible.builtin.shell: systemctl enable nginx

# systemctl restart nginx &>>$log_file
- name: Restart Nginx
  ansible.builtin.shell: systemctl restart nginx

