- name: Import Docker Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: docker-ce-install


- name: Start App container
  community.docker.docker_container:
    name: shipping
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
    ports:
      - "8080:8080"
    env:
      CART_ENDPOINT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/shipping:CART_ENDPOINT token={{ vault_token }} url=http://vault-internal.azdevopsv82.online:8200') }}"
      DB_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ ENV }}/shipping:DB_HOST token={{ vault_token }} url=http://vault-internal.azdevopsv82.online:8200') }}"

