####
- name: Disable Default NodeJS Version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS 20 Version
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

####
- name: Create Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove application directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /app
    remote_src: yes

####
- name:  Copy MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

####
- name: Setup SystemD service file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Application
  ansible.builtin.systemd_service:
    name: catalogue
    state: restarted
    enabled: true
    daemon_reload: true

####
- name: Load Master Data
  community.mongodb.mongodb_shell:
    login_host: mongodb-{{ ENV }}.azdevopsv82.online
    file: "/app/db/master-data.js"
    idempotent: yes
