#echo Disable Default NodeJS Version
#dnf module disable nodejs -y &>>$log_file
#Status_Print $?
- name: Disable NodeJS Version
  ansible.builtin.shell: dnf module disable nodejs -y

#echo Enable NodeJS 20 Version
#dnf module enable nodejs:20 -y &>>$log_file
#Status_Print $?
- name: Enable NodeJS 20 Version
  ansible.builtin.shell: dnf module enable nodejs:20 -y

#echo Install NodeJS
#dnf install nodejs -y &>>$log_file
#Status_Print $?
- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed

#APP_PREREQ
- name: Import App Prerequisites
  ansible.builtin.include_tasks:
    file: app-prereq.yml

#echo Install NodeJS Dependencies
#npm install &>>$log_file
- name: Install NodeJS Dependencies
  community.general.npm:
    path: /app

#Status_Print $?
#
#SYSTEMD_SETUP
- name: Import Systemd
  ansible.builtin.include_tasks:
    file: systemd.yml