- name: Create application user
  ansible.builtin.user:
    name: roboshop

- name: Remove application directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ appl }}-v3.zip
    dest: /app
    remote_src: yes

- name: Install dependencies
  community.general.npm:
    path: /app
