- name: Setup systemD service file
  ansible.builtin.template:
    src: "{{ appl }}.service"
    dest: /etc/systemd/system/{{ appl }}.service

- name: Enable and start application with daemon
  ansible.builtin.systemd_service:
    name: {{ appl }}
    enabled: true
    state: restarted
    daemon_reload: true